project:
  group: sedemo-team-webinar

image:
  # If using default workflow, this will be set to ghcr.io/<github_org>/<repo_name>
  repository: ghcr.io/akuity/sedemo-app-feb
  # Default use of this ghcr publishing workflow will use incrmental build number as tag
  selectionStrategy: Lexical
  # if useing digest stragey, uncomment next line and comment tagRegex line
  #tag: latest
  tagRegex: '^\d*$'
  containerPort: 80
  memoryLimit: 128Mi
  cpuLimit: 1m
ingress:
  custom_prefix: feb

rollouts:
  enabled: true

environments:
  staging: true
